source 'https://rubygems.org'
gem 'dentaku'
gem 'discordrb', git: 'https://github.com/FormalHellhound/discordrb.git', branch: 'improvements/permitted_roles'
gem 'googl'
gem 'kappa', git: 'https://github.com/FormalHellhound/kappa.git', branch: 'api-v5'
gem 'myanimelist', git: 'https://github.com/FormalHellhound/myanimelist.git'
gem 'pastebin-api'
gem 'rmagick'
gem 'rounding'
gem 'rubocop'
gem 'ruby-cleverbot-api'
gem 'ruby-mp3info'
gem 'sqlite3'
gem 'wikipedia-client'
gem 'yajl-ruby'
gem 'yourub'
gem 'youtube-dl.rb', git: 'https://github.com/grcdeepak1/youtube-dl.rb.git'
