source 'https://rubygems.org'
gem 'dentaku'
gem 'discordrb', git: 'https://github.com/FormalHellhound/discordrb.git', branch: 'improvements/permitted_roles'
gem 'googl'
gem 'kappa'
gem 'myanimelist', git: 'https://github.com/FormalHellhound/myanimelist.git'
gem 'pastebin-api'
gem 'rounding'
gem 'rubocop'
gem 'ruby_cleverbot', git: 'https://github.com/FormalHellhound/ruby_cleverbot.git'
gem 'sqlite3'
gem 'wikipedia-client'
gem 'yajl-ruby'
gem 'yourub'
